[package]
name = "ristretto"
version = "0.1.0"
authors = ["Al Liu <scygliu1@gmail.com>"]
description = "This is a Rust implementation for Dgraph's ristretto."
homepage = "https://github.com/al8n/ristretto"
repository = "https://github.com/al8n/ristretto.git"
documentation = "https://docs.rs/ristretto/"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["cache", "data-structures"]
categories = ["algorithms", "data-structures"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["serde", "serde/derive", "serde_json/default"]
nightly = ["parking_lot/nightly",
    "rand/nightly",
    "crossbeam/nightly",
    "serde",
    "serde/derive",
    "serde_json/default"
]

[dependencies]
atomic = "0.5.0"
crossbeam = "0.8.1"
chrono = "0.4.19"
caches = "0.2.0"
log = "0.4.14"
lazy_static = "1.4.0"
parking_lot = "0.11.2"
rand = "0.8.4"
serde = {version = "1", optional = true}
serde_json = {version = "1.0", optional = true}
twox-hash = "1.6.1"

[dev-dependencies]
loom = "0.5.1"