[package]
name = "stretto"
version = "0.1.1"
authors = ["Al Liu <scygliu1@gmail.com>"]
description = "Stretto is a high performance thread-safe memory-bound Rust cache."
homepage = "https://github.com/al8n/stretto"
repository = "https://github.com/al8n/stretto.git"
documentation = "https://docs.rs/stretto/"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["cache", "caching", "concurrent", "tinylfu", "async"]
categories = ["caching", "concurrency", "asynchronous"]
edition = "2018"

[[example]]
path = "examples/async_example.rs"
name = "async_example"
required-features = ["async"]
edition = "2018"

[[example]]
path = "examples/sync_example.rs"
name = "sync_example"
required-features = ["sync"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["sync"]
async = ["tokio/rt-multi-thread", "tokio/test-util", "tokio/macros", "tokio/parking_lot"]
sync = ["crossbeam-channel", "crossbeam-utils"]
serilization = ["serde", "serde/derive", "serde_json/default"]

[dependencies]
atomic = "0.5.0"
crossbeam-channel = { version = "0.5.1", optional = true }
crossbeam-utils = { version = "0.8.5", optional = true }
log = { version = "0.4.14", optional = true }
parking_lot = "0.11.2"
rand = "0.8.4"
serde = {version = "1", optional = true}
serde_json = {version = "1.0", optional = true}
tokio = { version = "1.12.0", optional = true }
twox-hash = "1.6.1"