[package]
name = "ristretto"
version = "0.1.0"
authors = ["Al Liu <scygliu1@gmail.com>"]
description = "This is a Rust implementation for Dgraph's ristretto."
homepage = "https://github.com/al8n/ristretto"
repository = "https://github.com/al8n/ristretto.git"
documentation = "https://docs.rs/ristretto/"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["cache", "data-structures"]
categories = ["algorithms", "data-structures"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["sync"]
nightly = ["parking_lot/nightly",
    "rand/nightly",
    "serde",
    "serde/derive",
    "serde_json/default"
]
serilization = ["serde", "serde/derive", "serde_json/default"]
async = ["tokio/rt-multi-thread", "tokio/test-util", "tokio/macros", "tokio/parking_lot", "serilization"]
sync = ["serilization", "crossbeam-channel", "crossbeam-utils"]


[dependencies]
atomic = "0.5.0"
crossbeam-channel = { version = "0.5.1", optional = true }
crossbeam-utils = { version = "0.8.5", optional = true }
log = { version = "0.4.14", optional = true }
parking_lot = "0.11.2"
rand = "0.8.4"
serde = {version = "1", optional = true}
serde_json = {version = "1.0", optional = true}
tokio = { version = "1.12.0", optional = true }
twox-hash = "1.6.1"